// controllers/authController.js
import User from '../models/User.js';
import Student from '../models/Student.js'; 
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import crypto from 'crypto';

/**
 * Helper to extract the 2-digit starting year prefix from a session string (e.g., "2027/2028" -> "27")
 */
const getSessionYearPrefix = (sessionStr) => {
  if (!sessionStr) return "26";
  const match = sessionStr.match(/^(\d{4})/);
  if (match) {
    return match[1].slice(-2);
  }
  return "26";
};

/**
 * @route   POST /api/auth/login
 * @desc    Authenticate administrative, staff, and student personnel
 * @access  Public
 */
export const loginUser = async (req, res) => {
  try {
    const { usernameOrEmail, password } = req.body;

    if (!usernameOrEmail || !password) {
      return res.status(400).json({
        success: false,
        message: "Please provide both username/email and password."
      });
    }

    const cleanIdentifier = usernameOrEmail.trim();

    // Explicitly query +password so Mongoose returns the field if set to select: false in model
    const user = await User.findOne({
      $or: [
        { email: cleanIdentifier.toLowerCase() },
        { username: cleanIdentifier }
      ]
    }).select('+password');

    if (!user) {
      return res.status(400).json({ 
        success: false, 
        message: "Invalid credentials recorded." 
      });
    }

    // Safely evaluate hashed passwords or plain text legacy fallbacks
    let isMatch = false;
    try {
      isMatch = await bcrypt.compare(password, user.password);
    } catch (err) {
      isMatch = (password === user.password);
    }

    if (!isMatch && password === user.password) {
      isMatch = true;
    }

    if (!isMatch) {
      return res.status(400).json({ 
        success: false, 
        message: "Invalid credentials recorded." 
      });
    }

    // Generate JWT Auth Token
    const token = jwt.sign(
      { 
        id: user._id, 
        role: user.role,
        isClassTeacher: user.isClassTeacher || false,
        classTeacherOf: user.classTeacherOf || ''
      },
      process.env.JWT_SECRET || 'fallbackSecretKey',
      { expiresIn: '1d' }
    );

    return res.status(200).json({
      success: true,
      message: `Welcome back, ${user.name}`,
      token,
      user: {
        id: user._id,
        name: user.name,
        surname: user.surname,
        firstName: user.firstName,
        email: user.email,
        username: user.username,
        role: user.role,
        schoolSection: user.schoolSection,
        assignedClass: user.assignedClass,
        isClassTeacher: Boolean(user.isClassTeacher), // 🟢 INCLUDED CLASS TEACHER FLAG
        classTeacherOf: user.classTeacherOf || '',     // 🟢 INCLUDED MANAGED CLASS NAME
        subjectAllocations: user.subjectAllocations || [],
        assignedClasses: user.assignedClasses || [],
        assignedSubjects: user.assignedSubjects || []
      }
    });

  } catch (error) {
    console.error("💥 Auth Pipeline Exception:", error);
    return res.status(500).json({ 
      success: false, 
      message: "Server error during authentication.",
      error: error.message 
    });
  }
};

/**
 * @route   POST /api/auth/register-student
 * @desc    Enroll a brand new student profile into the system with random, secure numeric credentials
 * @access  Private (Admin Control Panel)
 */
export const registerStudent = async (req, res) => {
  let createdBaseUser = null; 
  
  try {
    const { 
      surname, 
      firstName, 
      otherName, 
      currentClass, 
      admittedSession,
      gender, 
      email, 
      phone, 
      stateOfOrigin,
      fatherName,
      fatherPhone,
      motherName,
      motherPhone,
      guardianAddress
    } = req.body;

    if (!surname || !firstName || !currentClass || !admittedSession || !email) {
      return res.status(400).json({
        success: false,
        message: "Please fill out all required core fields."
      });
    }

    const existingEmail = await User.findOne({ email: email.toLowerCase().trim() });
    if (existingEmail) {
      return res.status(400).json({
        success: false,
        message: "A user record with this email address already exists."
      });
    }

    const sessionYearShort = getSessionYearPrefix(admittedSession);
    
    let autoGeneratedRegNo;
    let isUsernameTaken = true;

    while (isUsernameTaken) {
      const randomNumericSuffix = Math.floor(1000 + crypto.randomInt(0, 9000));
      autoGeneratedRegNo = `RC/${sessionYearShort}/${randomNumericSuffix}`;
      
      const userCheck = await User.findOne({ username: autoGeneratedRegNo });
      if (!userCheck) {
        isUsernameTaken = false; 
      }
    }

    const normalizedName = firstName.trim().replace(/[^a-zA-Z]/g, '');
    const cleanFirstName = normalizedName.charAt(0).toUpperCase() + normalizedName.slice(1).toLowerCase();
    const randomToken = Math.floor(1000 + Math.random() * 9000);
    const temporaryPassword = `${cleanFirstName}#${randomToken}`;

    const fullName = `${firstName.trim()} ${surname.trim()} ${otherName ? otherName.trim() : ''}`.replace(/\s+/g, ' ').trim();

    let passportPhotoUrl = "";
    if (req.file && req.file.path) {
      passportPhotoUrl = req.file.path; 
    }

    createdBaseUser = await User.create({
      name: fullName,
      surname: surname.trim(),
      firstName: firstName.trim(),
      username: autoGeneratedRegNo,
      email: email.toLowerCase().trim(),
      password: temporaryPassword,
      role: 'student'
    });

    const newStudent = await Student.create({
      ...req.body, 
      user: createdBaseUser._id, 
      name: fullName,
      admissionNo: autoGeneratedRegNo,
      regNumber: autoGeneratedRegNo, 
      username: autoGeneratedRegNo, 
      currentClass: currentClass.trim(), 
      admittedSession: admittedSession.trim(),
      gender: gender ? gender.trim() : "Not Specified",
      email: email.toLowerCase().trim(),
      phone: phone ? phone.trim() : null,
      stateOfOrigin: stateOfOrigin ? stateOfOrigin.trim() : null,
      password: temporaryPassword, 
      passportPhoto: passportPhotoUrl, 
      role: 'student',

      fatherName: fatherName ? fatherName.trim() : "",
      fatherPhone: fatherPhone ? fatherPhone.trim() : "",
      motherName: motherName ? motherName.trim() : "",
      motherPhone: motherPhone ? motherPhone.trim() : "",
      guardianAddress: guardianAddress ? guardianAddress.trim() : ""
    });

    return res.status(201).json({
      success: true,
      message: "Student profile registered within core engine database matrix.",
      student: {
        id: newStudent._id,
        name: newStudent.name,
        admissionNo: newStudent.admissionNo,
        currentClass: newStudent.currentClass,
        passportPhoto: newStudent.passportPhoto
      },
      credentials: {
        username: autoGeneratedRegNo,
        temporaryPassword: temporaryPassword
      }
    });

  } catch (error) {
    if (createdBaseUser) {
      await User.deleteOne({ _id: createdBaseUser._id }).catch((err) => 
        console.error("⚠️ Failed cleaning up orphan record:", err)
      );
    }

    console.error("💥 Student enrollment pipeline exception:", error);
    return res.status(500).json({
      success: false,
      message: "Internal server error during student entry creation.",
      error: error.message
    });
  }
};

/**
 * @route   GET /api/auth/students
 * @desc    Fetch active enrolled student records with server-side pagination and filters
 * @access  Private
 */
export const getAllStudents = async (req, res) => {
  try {
    const page = parseInt(req.query.page, 10) || 1;
    const limit = parseInt(req.query.limit, 10) || 50;
    const skipIndex = (page - 1) * limit;

    const queryFilters = {};

    if (req.query.search) {
      queryFilters.$or = [
        { name: { $regex: req.query.search, $options: "i" } },
        { admissionNo: { $regex: req.query.search, $options: "i" } }
      ];
    }
    
    // Support assignedClass or currentClass flex lookup
    if (req.query.assignedClass || req.query.currentClass) {
      const cls = (req.query.assignedClass || req.query.currentClass).trim();
      const classRegex = new RegExp(`^${cls.replace(/\s+/g, '\\s*')}$`, 'i');
      queryFilters.$or = [
        { currentClass: classRegex },
        { assignedClass: classRegex },
        { className: classRegex }
      ];
    }

    if (req.query.admittedSession) {
      queryFilters.admittedSession = req.query.admittedSession;
    }

    const [totalStudents, students] = await Promise.all([
      Student.countDocuments(queryFilters),
      Student.find(queryFilters)
        .sort({ surname: 1, firstName: 1 })
        .skip(skipIndex)
        .limit(limit)
        .lean()
    ]);

    const totalPages = Math.ceil(totalStudents / limit);

    return res.status(200).json({
      success: true,
      students,
      pagination: {
        totalRecords: totalStudents,
        currentPage: page,
        totalPages: totalPages,
        limit: limit,
        hasPrevPage: page > 1,
        hasNextPage: page < totalPages
      }
    });

  } catch (error) {
    console.error("💥 Student collection stream pipeline exception:", error);
    return res.status(500).json({
      success: false,
      message: "Internal server error streaming active student profiles.",
      error: error.message
    });
  }
};

/**
 * @route   GET /api/auth/dashboard-stats
 * @desc    Fetch live counts for the admin dashboard overview metrics
 */
export const getDashboardStats = async (req, res) => {
  try {
    const totalStudents = await Student.countDocuments({});
    
    const activeTeachers = await User.countDocuments({ 
      role: { $in: ['teacher', 'principal', 'TEACHER', 'PRINCIPAL'] } 
    });

    return res.status(200).json({
      success: true,
      stats: {
        totalStudents,
        activeTeachers,
        databaseLink: "127.0.0.1" 
      }
    });
  } catch (error) {
    console.error("💥 Dashboard statistics pipeline exception:", error);
    return res.status(500).json({
      success: false,
      message: "Internal server error gathering dashboard overview metrics.",
      error: error.message
    });
  }
};

/**
 * @route   PUT /api/auth/update-password
 */
export const updatePassword = async (req, res) => {
  try {
    const { currentPassword, newPassword } = req.body;
    const userId = req.user.id; 

    if (!currentPassword || !newPassword) {
      return res.status(400).json({ 
        success: false, 
        message: "Please provide both your current and new password." 
      });
    }

    const user = await User.findById(userId).select('+password');
    if (!user) {
      return res.status(404).json({ success: false, message: "User profile not found." });
    }

    let isMatch = false;
    try {
      isMatch = await bcrypt.compare(currentPassword, user.password);
    } catch (err) {
      isMatch = (currentPassword === user.password);
    }

    if (!isMatch && currentPassword === user.password) {
      isMatch = true;
    }

    if (!isMatch) {
      return res.status(400).json({ success: false, message: "Your current password context is incorrect." });
    }

    const salt = await bcrypt.genSalt(10);
    const hashedPassword = await bcrypt.hash(newPassword, salt);

    user.password = hashedPassword;
    await user.save();

    if (user.role === 'student') {
      await Student.findOneAndUpdate({ user: user._id }, { password: hashedPassword });
    }

    return res.status(200).json({
      success: true,
      message: "Password upgraded cleanly into secure systems architecture."
    });

  } catch (error) {
    console.error("💥 Password migration pipeline error:", error);
    return res.status(500).json({ 
      success: false, 
      message: "Internal server error upgrading credential properties." 
    });
  }
};